service: my-service

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  myFunction:
    handler: src/handler.handler
    events:
      - http:
          path: /
          method: get
